/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as ChatSettingsRouteImport } from './routes/_chat.settings'
import { Route as ChatActivityRouteImport } from './routes/_chat.activity'
import { Route as ChatThreadIdRouteImport } from './routes/_chat.$threadId'
import { Route as ChatProjectsProjectIdSettingsRouteImport } from './routes/_chat.projects.$projectId.settings'

const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const ChatSettingsRoute = ChatSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ChatRoute,
} as any)
const ChatActivityRoute = ChatActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => ChatRoute,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatProjectsProjectIdSettingsRoute =
  ChatProjectsProjectIdSettingsRouteImport.update({
    id: '/projects/$projectId/settings',
    path: '/projects/$projectId/settings',
    getParentRoute: () => ChatRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/$threadId': typeof ChatThreadIdRoute
  '/activity': typeof ChatActivityRoute
  '/settings': typeof ChatSettingsRoute
  '/projects/$projectId/settings': typeof ChatProjectsProjectIdSettingsRoute
}
export interface FileRoutesByTo {
  '/$threadId': typeof ChatThreadIdRoute
  '/activity': typeof ChatActivityRoute
  '/settings': typeof ChatSettingsRoute
  '/': typeof ChatIndexRoute
  '/projects/$projectId/settings': typeof ChatProjectsProjectIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/_chat/$threadId': typeof ChatThreadIdRoute
  '/_chat/activity': typeof ChatActivityRoute
  '/_chat/settings': typeof ChatSettingsRoute
  '/_chat/': typeof ChatIndexRoute
  '/_chat/projects/$projectId/settings': typeof ChatProjectsProjectIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$threadId'
    | '/activity'
    | '/settings'
    | '/projects/$projectId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$threadId'
    | '/activity'
    | '/settings'
    | '/'
    | '/projects/$projectId/settings'
  id:
    | '__root__'
    | '/_chat'
    | '/_chat/$threadId'
    | '/_chat/activity'
    | '/_chat/settings'
    | '/_chat/'
    | '/_chat/projects/$projectId/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/settings': {
      id: '/_chat/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ChatSettingsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/activity': {
      id: '/_chat/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ChatActivityRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/$threadId': {
      id: '/_chat/$threadId'
      path: '/$threadId'
      fullPath: '/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/projects/$projectId/settings': {
      id: '/_chat/projects/$projectId/settings'
      path: '/projects/$projectId/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof ChatProjectsProjectIdSettingsRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface ChatRouteChildren {
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ChatActivityRoute: typeof ChatActivityRoute
  ChatSettingsRoute: typeof ChatSettingsRoute
  ChatIndexRoute: typeof ChatIndexRoute
  ChatProjectsProjectIdSettingsRoute: typeof ChatProjectsProjectIdSettingsRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatThreadIdRoute: ChatThreadIdRoute,
  ChatActivityRoute: ChatActivityRoute,
  ChatSettingsRoute: ChatSettingsRoute,
  ChatIndexRoute: ChatIndexRoute,
  ChatProjectsProjectIdSettingsRoute: ChatProjectsProjectIdSettingsRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
